[package]
name = "web-alerts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre = "0.11"
curl = "0.4.46"
lazy_static = "1.4"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
